name: Build and deploy Node.js app to Azure Web App - Ark

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Clear npm cache and reinstall dependencies
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm cache clean --force
          npm install

      - name: Install dependencies
        run: npm ci  # Use npm ci to install dependencies from package-lock.json

      - name: Build the project
        run: npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .  # Adjust this path if necessary

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E341E00C43746AA842C0F1C79D3D9AD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6DAB1855597D43F3AE6B87508AD00BA1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CFB27113536942F3B6D5EEE0D0CC4700 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Ark'
          slot-name: 'Production'
          package: .  # Adjust this if your build output is in a specific folder